/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jproj;

import java.sql.*;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author akash
 */

public class frame5 extends javax.swing.JFrame {

    /**
     * Creates new form frame5
     */
    public frame5() {
        initComponents();
        setSize(998, 680);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        dish1 = new javax.swing.JButton();
        dish2 = new javax.swing.JButton();
        dish3 = new javax.swing.JButton();
        dish4 = new javax.swing.JButton();
        dish5 = new javax.swing.JButton();
        dish6 = new javax.swing.JButton();
        dish7 = new javax.swing.JButton();
        dish8 = new javax.swing.JButton();
        dish9 = new javax.swing.JButton();
        dish10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        sp1 = new javax.swing.JSpinner();
        sp2 = new javax.swing.JSpinner();
        sp3 = new javax.swing.JSpinner();
        sp5 = new javax.swing.JSpinner();
        sp6 = new javax.swing.JSpinner();
        sp7 = new javax.swing.JSpinner();
        sp8 = new javax.swing.JSpinner();
        sp9 = new javax.swing.JSpinner();
        sp10 = new javax.swing.JSpinner();
        sp11 = new javax.swing.JSpinner();
        bill = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        sp4 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0,80));

        dish1.setBackground(new java.awt.Color(228, 142, 55));
        dish1.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        dish1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dish1ActionPerformed(evt);
            }
        });

        dish2.setBackground(new java.awt.Color(228, 142, 55));
        dish2.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        dish2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dish2ActionPerformed(evt);
            }
        });

        dish3.setBackground(new java.awt.Color(228, 142, 55));
        dish3.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        dish3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dish3ActionPerformed(evt);
            }
        });

        dish4.setBackground(new java.awt.Color(228, 142, 55));
        dish4.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        dish4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dish4ActionPerformed(evt);
            }
        });

        dish5.setBackground(new java.awt.Color(228, 142, 55));
        dish5.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        dish5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dish5ActionPerformed(evt);
            }
        });

        dish6.setBackground(new java.awt.Color(228, 142, 55));
        dish6.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        dish6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dish6ActionPerformed(evt);
            }
        });

        dish7.setBackground(new java.awt.Color(228, 142, 55));
        dish7.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        dish7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dish7ActionPerformed(evt);
            }
        });

        dish8.setBackground(new java.awt.Color(228, 142, 55));
        dish8.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        dish8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dish8ActionPerformed(evt);
            }
        });

        dish9.setBackground(new java.awt.Color(228, 142, 55));
        dish9.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        dish9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dish9ActionPerformed(evt);
            }
        });

        dish10.setBackground(new java.awt.Color(228, 142, 55));
        dish10.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        dish10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dish10ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ORDER ");

        sp1.setEnabled(false);

        sp2.setEnabled(false);

        sp3.setEnabled(false);

        sp5.setEnabled(false);

        sp6.setEnabled(false);

        sp7.setEnabled(false);

        sp8.setEnabled(false);

        sp9.setEnabled(false);

        sp10.setEnabled(false);

        sp11.setEnabled(false);

        bill.setBackground(new java.awt.Color(51, 204, 0));
        bill.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        bill.setForeground(new java.awt.Color(102, 102, 102));
        bill.setText("CONFIRM");
        bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dish1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dish2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dish5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dish6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dish8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dish9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dish10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dish4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dish3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dish7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(sp1)
                                .addComponent(sp2)
                                .addComponent(sp3)
                                .addComponent(sp5))
                            .addComponent(sp7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(bill)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(sp1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                                                    .addComponent(dish1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(dish2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(sp2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(sp3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(dish3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(sp5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(dish4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                                .addComponent(dish5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(sp6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(sp7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bill, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(16, 16, 16))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(dish6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sp8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dish7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(dish8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(sp9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(dish9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sp10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dish10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 490, 620));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\akash\\OneDrive\\Pictures\\Saved Pictures\\order3.jpg")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 998, 680));
        jLabel2.getAccessibleContext().setAccessibleName("");

        sp4.setEnabled(false);
        jPanel1.add(sp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int qty1,qty2,qty3,qty4,qty5,qty6,qty7,qty8,qty9,qty10;
    
    private void dish2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dish2ActionPerformed
        // TODO add your handling code here:
        sp2.setEnabled(true);
        sp2.addChangeListener(new javax.swing.event.ChangeListener() {
    public void stateChanged(javax.swing.event.ChangeEvent evt) {
        qty2 = (int)sp2.getValue();
        
    }
});
    }//GEN-LAST:event_dish2ActionPerformed

    private void dish1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dish1ActionPerformed
        // TODO add your handling code here:
        sp1.setEnabled(true);
        sp1.addChangeListener(new javax.swing.event.ChangeListener() {
    public void stateChanged(javax.swing.event.ChangeEvent evt) {
        qty1 = (int)sp1.getValue();
        
    }
});
        //qty1 = qty1 + q;
    }//GEN-LAST:event_dish1ActionPerformed

    private void dish3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dish3ActionPerformed
        // TODO add your handling code here:
        sp3.setEnabled(true);
        sp3.addChangeListener(new javax.swing.event.ChangeListener() {
    public void stateChanged(javax.swing.event.ChangeEvent evt) {
        qty3 = (int)sp3.getValue();
        
    }
});
    }//GEN-LAST:event_dish3ActionPerformed

    private void dish4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dish4ActionPerformed
        // TODO add your handling code here:
        sp5.setEnabled(true);
        sp5.addChangeListener(new javax.swing.event.ChangeListener() {
    public void stateChanged(javax.swing.event.ChangeEvent evt) {
        qty4 = (int)sp5.getValue();
        
    }
});
    }//GEN-LAST:event_dish4ActionPerformed

    private void dish5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dish5ActionPerformed
        // TODO add your handling code here:
        sp6.setEnabled(true);
        sp6.addChangeListener(new javax.swing.event.ChangeListener() {
    public void stateChanged(javax.swing.event.ChangeEvent evt) {
        qty5 = (int)sp6.getValue();
        
    }
});
    }//GEN-LAST:event_dish5ActionPerformed

    private void dish6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dish6ActionPerformed
        // TODO add your handling code here:
        sp7.setEnabled(true);
        sp7.addChangeListener(new javax.swing.event.ChangeListener() {
    public void stateChanged(javax.swing.event.ChangeEvent evt) {
        qty6 = (int)sp7.getValue();
        
    }
});
    }//GEN-LAST:event_dish6ActionPerformed

    private void dish7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dish7ActionPerformed
        // TODO add your handling code here:
        sp8.setEnabled(true);
        sp8.addChangeListener(new javax.swing.event.ChangeListener() {
    public void stateChanged(javax.swing.event.ChangeEvent evt) {
        qty7 = (int)sp8.getValue();
        
    }
});
    }//GEN-LAST:event_dish7ActionPerformed

    private void dish8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dish8ActionPerformed
        // TODO add your handling code here:
        sp9.setEnabled(true);
        sp9.addChangeListener(new javax.swing.event.ChangeListener() {
    public void stateChanged(javax.swing.event.ChangeEvent evt) {
        qty8 = (int)sp9.getValue();
        
    }
});
    }//GEN-LAST:event_dish8ActionPerformed

    private void dish9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dish9ActionPerformed
        // TODO add your handling code here:
        sp10.setEnabled(true);
        sp10.addChangeListener(new javax.swing.event.ChangeListener() {
    public void stateChanged(javax.swing.event.ChangeEvent evt) {
        qty9 = (int)sp10.getValue();
        
    }
});
    }//GEN-LAST:event_dish9ActionPerformed

    private void dish10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dish10ActionPerformed
        // TODO add your handling code here:
        sp11.setEnabled(true);
       sp11.addChangeListener(new javax.swing.event.ChangeListener() {
    public void stateChanged(javax.swing.event.ChangeEvent evt) {
        qty10 = (int)sp11.getValue();
        
    }
});
    }//GEN-LAST:event_dish10ActionPerformed

    private void billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billActionPerformed
        // TODO add your handling code here:
    int result = JOptionPane.showConfirmDialog(this, "Are you sure?", "Confirmation", JOptionPane.OK_CANCEL_OPTION);
    if (result == JOptionPane.OK_OPTION) {
        // OK button clicked, perform desired action
        frame4 f4 = new frame4();
        f4.setVisible(true);
        try{  
//step1 load the driver class  
Class.forName("oracle.jdbc.driver.OracleDriver");  
  
//step2 create  the connection object  
Connection con=DriverManager.getConnection(  
"jdbc:oracle:thin:@localhost:1521:xe","abi","abi");  
  
//step3 create the statement object  
Statement stmt=con.createStatement(); 
ResultSet  tt = stmt.executeQuery("SELECT TO_CHAR(SYSDATE, 'HH24:MI:SS') AS time FROM dual");
//ResultSet  ti = stmt.executeQuery("select to_char(sysdate,'HH24:MI:SS') FROM dual");
//ResultSet  date = stmt.executeQuery("select trunc(sysdate) from dual");


SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");
Date current = new Date();
String formattedTime = timeFormat.format(current); 
f4.time.setText(formattedTime);

SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
Date currentDate = new Date();
String formattedDate = dateFormat.format(currentDate);
f4.date.setText(formattedDate);

    tt.next();
    Time currentTime = tt.getTime("time");
    System.out.println(currentTime);
    // Step 4: Compare the current time to determine the time period
    float tot = 0;
    if (currentTime.compareTo(Time.valueOf("12:00:00")) < 0) {
        ResultSet rs=stmt.executeQuery("select * from menu1"); 
        f4.bt.append("\n" +"ITEM NAME" + "\t\t\t\t" + "PRICE" + "\n");
        while(rs.next())  
        {

                String id = rs.getString(1);
               
                 if(id.equals("1") && qty1 != 0)
                 {
                    String name = dish1.getText();
                    System.out.println(name);
                    float amt = rs.getFloat(3);
                    amt = qty1 * amt;
                    String price = String.valueOf(amt);
                    tot = tot + amt;
                    f4.bt.append("\n" +name + "\t\t\t\t" + price + "\n");
                 }
                 if(id.equals ("2") && qty2 != 0){
                    String name = dish2.getText();
                    float amt = rs.getFloat(3);
                    amt = qty2 * amt;
                    String price = String.valueOf(amt);
                     tot = tot + amt;
                    f4.bt.append("\n" +name + "\t\t\t\t" + price + "\n");
                 }
                 if(id.equals ("3") && qty3 != 0){
                    String name = dish3.getText();
                    float amt = rs.getFloat(3);
                    amt = qty3 * amt;
                    String price = String.valueOf(amt);
                     tot = tot + amt;
                    f4.bt.append("\n" +name + "\t\t\t\t" + price + "\n");
                 }
                 if(id.equals ("4")&& qty4 != 0){
                    String name = dish4.getText();
                    float amt = rs.getFloat(3);
                    amt = qty4 * amt;
                    String price = String.valueOf(amt);
                     tot = tot + amt;
                    f4.bt.append("\n" +name + "\t\t\t\t" + price + "\n");
                 }
                 if(id.equals ("5")&& qty5 != 0){
                     String name = dish5.getText();
                    float amt = rs.getFloat(3);
                    amt = qty5 * amt;
                    String price = String.valueOf(amt);
                     tot = tot + amt;
                    f4.bt.append("\n" +name + "\t\t\t\t" + price + "\n");
                 }
                 if(id.equals ("6") && qty6 != 0){
                    String name = dish6.getText();
                    float amt = rs.getFloat(3);
                    amt = qty6 * amt;
                    String price = String.valueOf(amt);
                     tot = tot + amt;
                    f4.bt.append("\n" +name + "\t\t\t\t" + price + "\n");
                 }
                 if(id.equals ("7")&& qty7 != 0){
                    String name = dish7.getText();
                    float amt = rs.getFloat(3);
                    amt = qty7 * amt;
                    String price = String.valueOf(amt);
                     tot = tot + amt;
                   f4.bt.append("\n" +name + "\t\t\t\t" + price + "\n");
                 }
                 if(id.equals ("8") && qty8 != 0){
                    String name = dish8.getText();
                    float amt = rs.getFloat(3);
                    amt = qty8 * amt;
                    String price = String.valueOf(amt);
                     tot = tot + amt;
                   f4.bt.append("\n" +name + "\t\t\t\t" + price + "\n");
                 }
                 if(id.equals ("9") && qty9 != 0){
                     String name = dish9.getText();
                    float amt = rs.getFloat(3);
                    amt = qty9 * amt;
                    String price = String.valueOf(amt);
                     tot = tot + amt;
                    f4.bt.append("\n" +name + "\t\t\t\t" + price + "\n");
                 }
                 if(id.equals ("10") && qty10 != 0){
                    String name = dish10.getText();
                    float amt = rs.getFloat(3);
                    amt = qty10 * amt;
                    String price = String.valueOf(amt);
                     tot = tot + amt;
                   f4.bt.append("\n" +name + "\t\t\t\t\t" + price + "\n");
                 }
        }
        con.close(); 
       
        String bill_amt = String.valueOf(tot);
        f4.bt.append("\n\nTOTAL AMOUNT:"+"\t\t\t\t\tRs."+ bill_amt);
    } 
    else if (currentTime.compareTo(Time.valueOf("18:00:00")) < 0) {
        ResultSet rs=stmt.executeQuery("select * from menu2"); 
       
        while(rs.next())  
        {
            String id = rs.getString(1);
               
                 if(id.equals("1") && qty1 != 0)
                 {
                    String name = dish1.getText();
                    System.out.println(name);
                    float amt = rs.getFloat(3);
                    amt = qty1 * amt;
                    String price = String.valueOf(amt);
                    tot = tot + amt;
                    f4.bt.append("\n" +name + "\t\t\t\t" + price + "\n");
                 }
                 if(id.equals ("2") && qty2 != 0){
                    String name = dish2.getText();
                    float amt = rs.getFloat(3);
                    amt = qty2 * amt;
                    String price = String.valueOf(amt);
                     tot = tot + amt;
                    f4.bt.append("\n" +name + "\t\t\t\t" + price + "\n");
                 }
                 if(id.equals ("3") && qty3 != 0){
                    String name = dish3.getText();
                    float amt = rs.getFloat(3);
                    amt = qty3 * amt;
                    String price = String.valueOf(amt);
                     tot = tot + amt;
                    f4.bt.append("\n" +name + "\t\t\t\t" + price + "\n");
                 }
                 if(id.equals ("4")&& qty4 != 0){
                    String name = dish4.getText();
                    float amt = rs.getFloat(3);
                    amt = qty4 * amt;
                    String price = String.valueOf(amt);
                     tot = tot + amt;
                    f4.bt.append("\n" +name + "\t\t\t\t" + price + "\n");
                 }
                 if(id.equals ("5")&& qty5 != 0){
                     String name = dish5.getText();
                    float amt = rs.getFloat(3);
                    amt = qty5 * amt;
                    String price = String.valueOf(amt);
                     tot = tot + amt;
                    f4.bt.append("\n" +name + "\t\t\t\t" + price + "\n");
                 }
                 if(id.equals ("6") && qty6 != 0){
                    String name = dish6.getText();
                    float amt = rs.getFloat(3);
                    amt = qty6 * amt;
                    String price = String.valueOf(amt);
                     tot = tot + amt;
                    f4.bt.append("\n" +name + "\t\t\t\t" + price + "\n");
                 }
                 if(id.equals ("7")&& qty7 != 0){
                    String name = dish7.getText();
                    float amt = rs.getFloat(3);
                    amt = qty7 * amt;
                    String price = String.valueOf(amt);
                     tot = tot + amt;
                   f4.bt.append("\n" +name + "\t\t\t\t" + price + "\n");
                 }
                 if(id.equals ("8") && qty8 != 0){
                    String name = dish8.getText();
                    float amt = rs.getFloat(3);
                    amt = qty8 * amt;
                    String price = String.valueOf(amt);
                     tot = tot + amt;
                   f4.bt.append("\n" +name + "\t\t\t\t" + price + "\n");
                 }
                 if(id.equals ("9") && qty9 != 0){
                     String name = dish9.getText();
                    float amt = rs.getFloat(3);
                    amt = qty9 * amt;
                    String price = String.valueOf(amt);
                     tot = tot + amt;
                    f4.bt.append("\n" +name + "\t\t\t\t" + price + "\n");
                 }
                 if(id.equals ("10") && qty10 != 0){
                    String name = dish10.getText();
                    float amt = rs.getFloat(3);
                    amt = qty10 * amt;
                    String price = String.valueOf(amt);
                     tot = tot + amt;
                   f4.bt.append("\n" +name + "\t\t\t\t\t" + price + "\n");
                 }
        }
        con.close(); 
       
        String bill_amt = String.valueOf(tot);
        f4.bt.append("\n\n \tTOTAL AMOUNT:"+"\t\t\t\t\tRs."+ bill_amt);
           
    }
    else {
        ResultSet rs=stmt.executeQuery("select * from menu3"); 
        
        while(rs.next())  
        {
                 String id = rs.getString(1);
               
                 if(id.equals("1") && qty1 != 0)
                 {
                    String name = dish1.getText();
                    System.out.println(name);
                    float amt = rs.getFloat(3);
                    amt = qty1 * amt;
                    String price = String.valueOf(amt);
                    tot = tot + amt;
                    f4.bt.append("\n" +name + "\t\t\t\t" + price + "\n");
                 }
                 if(id.equals ("2") && qty2 != 0){
                    String name = dish2.getText();
                    float amt = rs.getFloat(3);
                    amt = qty2 * amt;
                    String price = String.valueOf(amt);
                     tot = tot + amt;
                    f4.bt.append("\n" +name + "\t\t\t\t" + price + "\n");
                 }
                 if(id.equals ("3") && qty3 != 0){
                    String name = dish3.getText();
                    float amt = rs.getFloat(3);
                    amt = qty3 * amt;
                    String price = String.valueOf(amt);
                     tot = tot + amt;
                    f4.bt.append("\n" +name + "\t\t\t\t" + price + "\n");
                 }
                 if(id.equals ("4")&& qty4 != 0){
                    String name = dish4.getText();
                    float amt = rs.getFloat(3);
                    amt = qty4 * amt;
                    String price = String.valueOf(amt);
                     tot = tot + amt;
                    f4.bt.append("\n" +name + "\t\t\t\t" + price + "\n");
                 }
                 if(id.equals ("5")&& qty5 != 0){
                     String name = dish5.getText();
                    float amt = rs.getFloat(3);
                    amt = qty5 * amt;
                    String price = String.valueOf(amt);
                     tot = tot + amt;
                    f4.bt.append("\n" +name + "\t\t\t\t" + price + "\n");
                 }
                 if(id.equals ("6") && qty6 != 0){
                    String name = dish6.getText();
                    float amt = rs.getFloat(3);
                    amt = qty6 * amt;
                    String price = String.valueOf(amt);
                     tot = tot + amt;
                    f4.bt.append("\n" +name + "\t\t\t\t" + price + "\n");
                 }
                 if(id.equals ("7")&& qty7 != 0){
                    String name = dish7.getText();
                    float amt = rs.getFloat(3);
                    amt = qty7 * amt;
                    String price = String.valueOf(amt);
                     tot = tot + amt;
                   f4.bt.append("\n" +name + "\t\t\t\t" + price + "\n");
                 }
                 if(id.equals ("8") && qty8 != 0){
                    String name = dish8.getText();
                    float amt = rs.getFloat(3);
                    amt = qty8 * amt;
                    String price = String.valueOf(amt);
                     tot = tot + amt;
                   f4.bt.append("\n" +name + "\t\t\t\t" + price + "\n");
                 }
                 if(id.equals ("9") && qty9 != 0){
                     String name = dish9.getText();
                    float amt = rs.getFloat(3);
                    amt = qty9 * amt;
                    String price = String.valueOf(amt);
                     tot = tot + amt;
                    f4.bt.append("\n" +name + "\t\t\t\t" + price + "\n");
                 }
                 if(id.equals ("10") && qty10 != 0){
                    String name = dish10.getText();
                    float amt = rs.getFloat(3);
                    amt = qty10 * amt;
                    String price = String.valueOf(amt);
                     tot = tot + amt;
                   f4.bt.append("\n" +name + "\t\t\t\t\t" + price + "\n");
                 }
        }
        con.close(); 
       
        String bill_amt = String.valueOf(tot);
        f4.bt.append("\n\n \tTOTAL AMOUNT: Rs."+ bill_amt);
           
    }
    }catch(Exception e){ System.out.println(e);} 

        
    } else if (result == JOptionPane.CANCEL_OPTION) {
        // Cancel button clicked, handle cancellation
    }
    }//GEN-LAST:event_billActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bill;
    public javax.swing.JButton dish1;
    public javax.swing.JButton dish10;
    public javax.swing.JButton dish2;
    public javax.swing.JButton dish3;
    public javax.swing.JButton dish4;
    public javax.swing.JButton dish5;
    public javax.swing.JButton dish6;
    public javax.swing.JButton dish7;
    public javax.swing.JButton dish8;
    public javax.swing.JButton dish9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner sp1;
    private javax.swing.JSpinner sp10;
    private javax.swing.JSpinner sp11;
    private javax.swing.JSpinner sp2;
    private javax.swing.JSpinner sp3;
    private javax.swing.JSpinner sp4;
    private javax.swing.JSpinner sp5;
    private javax.swing.JSpinner sp6;
    private javax.swing.JSpinner sp7;
    private javax.swing.JSpinner sp8;
    private javax.swing.JSpinner sp9;
    // End of variables declaration//GEN-END:variables
}
