/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jproj;

import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author akash
 */
public class frame3 extends javax.swing.JFrame {

    /**
     * Creates new form frame3
     */
    public frame3() {
        initComponents();
        setSize(1000, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        regno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        sign = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Brush Script MT", 0, 36)); // NOI18N
        jLabel2.setText("Just Think Inn");

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setText("Welcome Back");

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Sign in with your register no and password");

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Register no");

        regno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regnoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Password");

        sign.setBackground(new java.awt.Color(0, 153, 0));
        sign.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        sign.setForeground(new java.awt.Color(255, 255, 255));
        sign.setText("Sign in");
        sign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(regno, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sign, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(regno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(sign, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 670));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\akash\\OneDrive\\Pictures\\Saved Pictures\\bgfood10.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 1030, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regnoActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_regnoActionPerformed

    private void signActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signActionPerformed
        // TODO add your handling code here:
         String reg = regno.getText();
        String pass = password.getText();
        int r = 0;
        int p = 0;
        try{  
//step1 load the driver class  
Class.forName("oracle.jdbc.driver.OracleDriver");  
  
//step2 create  the connection object  
Connection con=DriverManager.getConnection(  
"jdbc:oracle:thin:@localhost:1521:xe","abi","abi");  
  
//step3 create the statement object  
Statement stmt=con.createStatement(); 
ResultSet rs=stmt.executeQuery("select * from cit_student"); 
        
        while(rs.next())  
        {
                String id = rs.getString(1);
                String pw = rs.getString(2);
                
                if(reg.equals(id))
                    r = 1;
                if(pass.equals(pw))
                    p = 1;         
        }
        con.close(); 
        }catch(Exception e){ System.out.println(e);} 
        
        if(r==1 && p==1)
        {//ImageIcon icon = new ImageIcon(getClass().getResource("jproj\\crt.jpg"));
        
        // Display the dialog box
        JOptionPane.showMessageDialog(null, "Logged in successfully");//"success", JOptionPane.INFORMATION_MESSAGE, icon);
        frame5 f5 = new frame5();
        f5.setVisible(true);
        try{  
//step1 load the driver class  
Class.forName("oracle.jdbc.driver.OracleDriver");  
  
//step2 create  the connection object  
Connection con=DriverManager.getConnection(  
"jdbc:oracle:thin:@localhost:1521:xe","abi","abi");  
  
//step3 create the statement object  
Statement stmt=con.createStatement(); 
ResultSet  tt = stmt.executeQuery("SELECT TO_CHAR(SYSDATE, 'HH24:MI:SS') AS time FROM dual");

    tt.next();
    Time currentTime = tt.getTime("time");
    System.out.println(currentTime);
    // Step 4: Compare the current time to determine the time period
    
    if (currentTime.compareTo(Time.valueOf("12:00:00")) < 0) {
        ResultSet rs=stmt.executeQuery("select * from menu1"); 
        
        while(rs.next())  
        {

                String id = rs.getString(1);
                 if(id.equals("1"))
                 {String name = rs.getString(2);
                 f5.dish1.setText(name);}
                 if(id.equals ("2")){
                     String name = rs.getString(2);
                     f5.dish2.setText(name);
                 }
                 if(id.equals ("3")){
                     String name = rs.getString(2);
                     f5.dish3.setText(name);
                 }
                 if(id.equals ("4")){
                     String name = rs.getString(2);
                     f5.dish4.setText(name);
                 }
                 if(id.equals ("5")){
                     String name = rs.getString(2);
                     f5.dish5.setText(name);
                 }
                 if(id.equals ("6")){
                     String name = rs.getString(2);
                     f5.dish6.setText(name);
                 }
                 if(id.equals ("7")){
                     String name = rs.getString(2);
                     f5.dish7.setText(name);
                 }
                 if(id.equals ("8")){
                     String name = rs.getString(2);
                     f5.dish8.setText(name);
                 }
                 if(id.equals ("9")){
                     String name = rs.getString(2);
                     f5.dish9.setText(name);
                 }
                 if(id.equals ("10")){
                     String name = rs.getString(2);
                     f5.dish10.setText(name);
                 }
        }
        con.close();  
    } 
    else if (currentTime.compareTo(Time.valueOf("18:00:00")) < 0) {
        ResultSet rs=stmt.executeQuery("select * from menu2"); 
       
        while(rs.next())  
        {

                String id = rs.getString(1);
                 if(id.equals("1"))
                 {String name = rs.getString(2);
                 f5.dish1.setText(name);}
                 if(id.equals ("2")){
                     String name = rs.getString(2);
                     f5.dish2.setText(name);
                 }
                 if(id.equals ("3")){
                     String name = rs.getString(2);
                     f5.dish3.setText(name);
                 }
                 if(id.equals ("4")){
                     String name = rs.getString(2);
                     f5.dish4.setText(name);
                 }
                 if(id.equals ("5")){
                     String name = rs.getString(2);
                     f5.dish5.setText(name);
                 }
                 if(id.equals ("6")){
                     String name = rs.getString(2);
                     f5.dish6.setText(name);
                 }
                 if(id.equals ("7")){
                     String name = rs.getString(2);
                     f5.dish7.setText(name);
                 }
                 if(id.equals ("8")){
                     String name = rs.getString(2);
                     f5.dish8.setText(name);
                 }
                 if(id.equals ("9")){
                     String name = rs.getString(2);
                     f5.dish9.setText(name);
                 }
                 if(id.equals ("10")){
                     String name = rs.getString(2);
                     f5.dish10.setText(name);
                 }
        }
        con.close();
           
    }
    else {
        ResultSet rs=stmt.executeQuery("select * from menu3"); 
        
        while(rs.next())  
        {
                 String id = rs.getString(1);
                 if(id.equals("1"))
                 {String name = rs.getString(2);
                 f5.dish1.setText(name);}
                 if(id.equals ("2")){
                     String name = rs.getString(2);
                     f5.dish2.setText(name);
                 }
                 if(id.equals ("3")){
                     String name = rs.getString(2);
                     f5.dish3.setText(name);
                 }
                 if(id.equals ("4")){
                     String name = rs.getString(2);
                     f5.dish4.setText(name);
                 }
                 if(id.equals ("5")){
                     String name = rs.getString(2);
                     f5.dish5.setText(name);
                 }
                 if(id.equals ("6")){
                     String name = rs.getString(2);
                     f5.dish6.setText(name);
                 }
                 if(id.equals ("7")){
                     String name = rs.getString(2);
                     f5.dish7.setText(name);
                 }
                 if(id.equals ("8")){
                     String name = rs.getString(2);
                     f5.dish8.setText(name);
                 }
                 if(id.equals ("9")){
                     String name = rs.getString(2);
                     f5.dish9.setText(name);
                 }
                 if(id.equals ("10")){
                     String name = rs.getString(2);
                     f5.dish10.setText(name);
                 }
                 
        }
        con.close(); 
           
    }
    }catch(Exception e){ System.out.println(e);} 

        }
        else if(r==0 && p==1){
            JOptionPane.showMessageDialog(this, "Invalid Register number ", "Error", JOptionPane.ERROR_MESSAGE);
            regno.setText("");
            password.setText("");
        }
        else if(r==1 && p==0){
            JOptionPane.showMessageDialog(this, "Invalid Password", "Error", JOptionPane.ERROR_MESSAGE);
            regno.setText("");
            password.setText("");
        }
        else if(r==0 && p==0){
            JOptionPane.showMessageDialog(this, "Invalid Register Number and Password", "Error", JOptionPane.ERROR_MESSAGE);
            regno.setText("");
            password.setText("");
        }
    }//GEN-LAST:event_signActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField regno;
    private javax.swing.JButton sign;
    // End of variables declaration//GEN-END:variables
}
